### ISSUE TITLE
Fails with vectors as map keys

### ISSUE THREAD

**Issue by rauhs** [marianoguerra/transito#1]
```
echo '[{[:a] :b}]'  | transito e2t -
  Traceback (most recent call last):
  File "/usr/local/bin/transito", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/transito/__init__.py", line 5, in main
    transito.main()
  File "/usr/local/lib/python2.7/dist-packages/transito/transito.py", line 215, in main
    print(handler(args))
  File "/usr/local/lib/python2.7/dist-packages/transito/transito.py", line 162, in edn_to_transit
    value = read_edn(args.path)
  File "/usr/local/lib/python2.7/dist-packages/transito/transito.py", line 123, in read_edn
    return edn.loads(handle.read())
  File "/usr/local/lib/python2.7/dist-packages/transito/edn.py", line 192, in loads
    return parser.parse(lexer.lex(code), state)
  File "/usr/local/lib/python2.7/dist-packages/rply/parser.py", line 23, in parse
    t, symstack, statestack, state
  File "/usr/local/lib/python2.7/dist-packages/rply/parser.py", line 82, in _reduce_production
    value = p.func(state, targ)
  File "/usr/local/lib/python2.7/dist-packages/transito/edn.py", line 99, in value_map
    return dict(p[1])
TypeError: unhashable type: 'list'
```

This is common to use for queries in om.next and is handled properly in transit-clj.

**Comment by marianoguerra** [comment]
check latest commit and new release, it should work: https://pypi.python.org/pypi/transito/0.1.5

thanks for reporting!

**Comment by rauhs** [comment]
That was quick. And it works! Thanks!
